# Generated by Django 3.1.4 on 2021-01-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
