# Generated by Django 3.1.4 on 2021-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiss',
            name='when',
            field=models.DateField(null=True),
        ),
    ]
